apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vuln-bank
  name: operator
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: vuln-bank
  name: operator-binding
subjects:
- kind: ServiceAccount
  name: operator
  namespace: vuln-bank
roleRef:
  kind: Role
  name: operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vuln-bank
  name: operator
