apiVersion: v1
kind: Pod
metadata:
  name: signed-vuln-bank
  namespace: vuln-bank
  labels:
    app: vuln-bank
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: vuln-bank
    image: ghcr.io/Ekene95/vuln-bank:hardened
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m
  automountServiceAccountToken: false
