apiVersion: v1
kind: Pod
metadata:
  name: unsigned-nginx
  namespace: vuln-bank
  labels:
    app: unsigned-test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    securityContext:
      runAsNonRoot: true
      runAsUser: 101
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      limits:
        memory: 128Mi
        cpu: 250m
      requests:
        memory: 64Mi
        cpu: 100m
  automountServiceAccountToken: false
